spring.application.name=notification-service
spring.config.import=optional:configserver:http://localhost:8888

server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=OmniChargeSecretKeyForJWTTokenGenerationAndValidation2024
jwt.expiration=86400000

# RabbitMQ - notification service listens to notification queue only
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.notification.queue=notification.queue

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.root=WARN
logging.level.com.omnicharge=WARN
logging.level.org.springframework=WARN
logging.level.com.netflix=WARN