spring.application.name=payment-service
spring.config.import=optional:configserver:http://localhost:8888

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

rabbitmq.payment.queue=payment.queue
rabbitmq.notification.queue=notification.queue

# Async Retry Configuration for recharge status update
app.retry.max-attempts=6
app.retry.interval-seconds=30

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Logging
logging.level.com.omnicharge=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate.SQL=OFF
logging.level.com.netflix=WARN
logging.level.root=WARN

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method

# Zipkin Distributed Tracing
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Payment Gateway Configuration
payment.gateway.valid-banks=SBI,HDFC,ICICI,AXIS,KOTAK,BOB,PNB,CANARA,UNION,INDUSIND

# Refund & Transaction
app.refund.eta=5-7 business days
app.transaction.id-prefix=TXN
