spring.application.name=recharge-service
spring.config.import=optional:configserver:http://localhost:8888

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/recharge_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=OmniChargeSecretKeyForJWTTokenGenerationAndValidation2024
jwt.expiration=86400000

# RabbitMQ - recharge service only publishes to payment queue
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.payment.queue=payment.queue

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.root=WARN
logging.level.com.omnicharge=WARN
logging.level.org.hibernate.SQL=OFF
logging.level.org.springframework=WARN
logging.level.com.netflix=WARN