spring.application.name=config-server
server.port=8888
spring.profiles.active=git

# Local Configuration (Currently Active)
spring.cloud.config.server.native.search-locations=classpath:/configs

# -------------------------------------------------------------
# GitHub Configuration (To switch, change active profile above to 'git')
# -------------------------------------------------------------
spring.cloud.config.server.git.uri=https://github.com/t-swami/omniCharge.git
spring.cloud.config.server.git.username=${CONFIG_REPO_USERNAME}
spring.cloud.config.server.git.password=${CONFIG_REPO_PASSWORD}
spring.cloud.config.server.git.clone-on-start=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Zipkin Distributed Tracing
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans